### PR TITLE
Revert "Fix memory leak caused by Cgo thread spawning"

### PR DESCRIPTION
**Pull request by QiJune**
Reverts wangkuiyi/gotorch#319

### CODE REVIEW

**Comment by QiJune** [comment]
Please refer to #321, it seems that runtime.LockOSThread will reduce throughput.

**Comment by shendiaomo** [comment]
> Please refer to #321, it seems that runtime.LockOSThread will reduce throughput.

How about call `runtime.LockOSThread` in `Module.To`?

**Comment by QiJune** [comment]
> How about call runtime.LockOSThread in Module.To?
@shendiaomo  I make a test, it does no help.

**Review by Yancey1989 — APPROVED** [review]
LGTM, the throughput reduced to `78 samples/sec` from `110 samples/sec` with calling `runtime.LockOSThread()`.

Test throughput command: 
```bash
$ go test . -run TestImageTgzLoaderHeavy -v
=== RUN   TestImageTgzLoaderHeavy
2020/09/14 07:19:41 throughput: 78.443666 samples/secs
2020/09/14 07:19:45 throughput: 78.229064 samples/secs
```

**Comment by wangkuiyi** [comment]
If we merge #328 , we don't need this PR.

**Pull request closed without merging**
